### ISSUE TITLE
Updating when setting job

### ISSUE THREAD

**Issue by Dorian-Fendrel** [i-kulgu/qb-jobmenu#2]
With the current script, the menu is not updating when a player is set to a new job and then toggle on or off duty. I was able to resolve this by:

Removing

RegisterNetEvent('QBCore:Client:OnJobUpdate', function(JobInfo)
    PlayerJob = JobInfo
    onDuty = PlayerJob.onduty
end)

and putting in:

RegisterNetEvent('QBCore:Client:OnJobUpdate', function(JobInfo)
    PlayerJob = JobInfo
end)

RegisterNetEvent('QBCore:Client:SetDuty', function(duty)
    onDuty = duty
end)

**Comment by i-kulgu** [comment]
> With the current script, the menu is not updating when a player is set to a new job and then toggle on or off duty. I was able to resolve this by:
> 
> Removing
> 
> RegisterNetEvent('QBCore:Client:OnJobUpdate', function(JobInfo) PlayerJob = JobInfo onDuty = PlayerJob.onduty end)
> 
> and putting in:
> 
> RegisterNetEvent('QBCore:Client:OnJobUpdate', function(JobInfo) PlayerJob = JobInfo end)
> 
> RegisterNetEvent('QBCore:Client:SetDuty', function(duty) onDuty = duty end)

I have put the changes in. Thnx for the input !
